/**
 * THE PARITY GATE.
 *
 * The TS engine must reproduce the Python engine's numbers on identical
 * inputs to 6 decimal places (Python rounds most stats to 4dp, so this is
 * exact-match). Fixtures are generated by tools/extract_parity_fixtures.py
 * and guarded on the Python side by tests/test_parity_fixtures.py — the two
 * engines cannot silently diverge.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
  computeAgreement,
  fleissKappa,
  iccOneway,
  normalizeUnitName,
  type AgreementPackView,
  type KeywordRule,
} from "../src/engine/agreement.js";
import {
  bannedElementsGate,
  runGate,
  termLintGate,
  wordCountGate,
} from "../src/engine/gates.js";
import {
  checkShipGates,
  computeScores,
  priorityScore,
  BLOCKING_BUILTINS,
  type ScoringPackView,
} from "../src/engine/scoring.js";
import { sequenceRatio } from "../src/engine/seqmatch.js";
import { sanitizeControlChars, stripFences } from "../src/engine/sanitize.js";
import {
  estimatePipelineCost,
  estimatePerLoopUsd,
  estimateTotalUsd,
} from "../src/engine/costs.js";
import { assembleForPersona } from "../src/engine/assembly.js";
import type { DocumentModel, ManifestEntry } from "../src/engine/manifest.js";

const PARITY_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "fixtures",
  "parity",
);

function loadFixture<T>(name: string): T {
  return JSON.parse(fs.readFileSync(path.join(PARITY_DIR, name), "utf-8")) as T;
}

/** Fixture NaN sentinel → NaN. */
function num(v: number | "NaN"): number {
  return v === "NaN" ? NaN : v;
}

function expectParity(actual: number, expected: number | "NaN", label: string): void {
  const exp = num(expected);
  if (Number.isNaN(exp)) {
    expect(actual, label).toBeNaN();
  } else {
    expect(actual, label).toBeCloseTo(exp, 6);
  }
}

interface PackJson {
  score_dimensions: string[];
  verdict_field: string;
  verdict_categories: string[];
  unit_field: string;
  unit_list_field: string;
  unit_score_field: string | null;
  unit_keyword_rules: [string, string][];
  ship_gates?: {
    composite_min: number;
    dimension_min: number;
    weights: Record<string, number> | null;
    composite_exclude_personas: string[];
    blocking: string | null;
  };
}

function agreementPack(pack: PackJson): AgreementPackView {
  return {
    scoreDimensions: pack.score_dimensions,
    verdictField: pack.verdict_field,
    verdictCategories: pack.verdict_categories,
    unitField: pack.unit_field,
    unitListField: pack.unit_list_field,
    unitScoreField: pack.unit_score_field,
    unitKeywordRules: pack.unit_keyword_rules as KeywordRule[],
  };
}

function scoringPack(pack: PackJson): ScoringPackView {
  const ship = pack.ship_gates!;
  return {
    scoreDimensions: pack.score_dimensions,
    unitField: pack.unit_field,
    unitListField: pack.unit_list_field,
    unitScoreField: pack.unit_score_field,
    unitKeywordRules: pack.unit_keyword_rules as KeywordRule[],
    shipGates: {
      compositeMin: ship.composite_min,
      dimensionMin: ship.dimension_min,
      weights: ship.weights,
      compositeExcludePersonas: ship.composite_exclude_personas,
      blockingFindings:
        ship.blocking === null ? null : BLOCKING_BUILTINS[ship.blocking]!,
    },
  };
}

describe("agreement parity", () => {
  interface Case {
    name: string;
    pack: PackJson;
    reviews: Record<string, unknown>[];
    personas: string[] | null;
    expected: Record<string, number | "NaN">;
  }
  const cases = loadFixture<Case[]>("agreement_cases.json");
  it.each(cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    const result = computeAgreement(c.reviews, agreementPack(c.pack), c.personas);
    expect(Object.keys(result).sort()).toEqual(Object.keys(c.expected).sort());
    for (const [key, exp] of Object.entries(c.expected)) {
      expectParity(result[key]!, exp, key);
    }
  });
});

describe("icc parity", () => {
  interface Case {
    name: string;
    scores: number[][];
    expected: number | "NaN";
  }
  const cases = loadFixture<Case[]>("icc_cases.json");
  it.each(cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    expectParity(iccOneway(c.scores), c.expected, c.name);
  });
});

describe("fleiss kappa parity", () => {
  interface Case {
    name: string;
    pack: PackJson;
    reviews: Record<string, unknown>[];
    expected: number | "NaN";
  }
  const cases = loadFixture<Case[]>("kappa_cases.json");
  it.each(cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    const kappa = fleissKappa(c.reviews, {
      verdictField: c.pack.verdict_field,
      verdictCategories: c.pack.verdict_categories,
      unitField: c.pack.unit_field,
      unitListField: c.pack.unit_list_field,
      keywordRules: c.pack.unit_keyword_rules as KeywordRule[],
    });
    expectParity(kappa, c.expected, c.name);
  });
});

describe("unit-name normalization parity", () => {
  interface Case {
    input: string;
    rules: [string, string][];
    expected: string;
  }
  const cases = loadFixture<Case[]>("normalize_cases.json");
  for (const c of cases) {
    it(`normalize(${JSON.stringify(c.input)})`, () => {
      expect(normalizeUnitName(c.input, c.rules as KeywordRule[])).toBe(c.expected);
    });
  }
});

describe("scoring + ship-gate parity", () => {
  interface Case {
    name: string;
    pack: PackJson;
    reviews: Record<string, unknown>[];
    personas: string[];
    synthesis: Record<string, unknown> | null;
    gate_results: Record<string, { passed: boolean; findings: string[] }>;
    expected: {
      composite: number | "NaN" | null;
      per_dimension: Record<string, number>;
      ship_ok: boolean;
      reasons: string[];
    };
  }
  const cases = loadFixture<Case[]>("scoring_cases.json");
  it.each(cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    const pack = scoringPack(c.pack);
    const personas = c.personas.length > 0 ? c.personas : null;
    const { composite, perDimension } = computeScores(c.reviews, pack, personas);
    if (c.expected.composite === null) {
      expect(composite).toBeNull();
    } else {
      expectParity(composite!, c.expected.composite, `${c.name}:composite`);
    }
    expect(Object.keys(perDimension).sort()).toEqual(
      Object.keys(c.expected.per_dimension).sort(),
    );
    for (const [dim, exp] of Object.entries(c.expected.per_dimension)) {
      expectParity(perDimension[dim]!, exp, `${c.name}:${dim}`);
    }

    const check = checkShipGates({
      synthesis: c.synthesis,
      reviews: c.reviews,
      gateResults: c.gate_results,
      pack,
      personas,
    });
    expect(check.ok, `${c.name}:ship_ok`).toBe(c.expected.ship_ok);
    expect(check.reasons, `${c.name}:reasons`).toEqual(c.expected.reasons);
  });
});

describe("priority-score parity", () => {
  interface Case {
    impact: number;
    ease: number;
    consensus: number;
    expected: number;
  }
  const cases = loadFixture<Case[]>("priority_cases.json");
  it("all 175 combinations", () => {
    for (const c of cases) {
      expect(
        priorityScore(c.impact, c.ease, c.consensus),
        `impact=${c.impact} ease=${c.ease} consensus=${c.consensus}`,
      ).toBeCloseTo(c.expected, 10);
    }
  });
});

describe("mechanical gate parity", () => {
  interface Case {
    gate: {
      type: string;
      max_words?: number;
      section?: string;
      line_prefix?: string;
      canonical_terms?: Record<string, string[]>;
      patterns?: string[];
    };
    text: string;
    expected: { name: string; passed: boolean; findings: string[] };
  }
  const cases = loadFixture<Case[]>("gate_cases.json");
  cases.forEach((c, i) => {
    it(`gate case ${i} (${c.gate.type})`, () => {
      const gate =
        c.gate.type === "word_count"
          ? wordCountGate(c.gate.max_words!, {
              section: c.gate.section ?? null,
              linePrefix: c.gate.line_prefix ?? null,
            })
          : c.gate.type === "term_lint"
            ? termLintGate(c.gate.canonical_terms!)
            : bannedElementsGate(c.gate.patterns!);
      expect(gate.name).toBe(c.expected.name);
      const result = runGate(gate, c.text);
      expect(result.passed).toBe(c.expected.passed);
      expect(result.findings).toEqual(c.expected.findings);
    });
  });
});

describe("SequenceMatcher ratio parity", () => {
  interface Case {
    a: string;
    b: string;
    expected: number;
  }
  const cases = loadFixture<Case[]>("sequence_matcher_cases.json");
  cases.forEach((c, i) => {
    it(`ratio case ${i}`, () => {
      expect(sequenceRatio(c.a, c.b)).toBeCloseTo(c.expected, 10);
    });
  });
});

describe("validation text-helper parity", () => {
  interface Case {
    fences: { input: string | null; expected_stripped: string }[];
    control_chars: { input: string | null; expected: string }[];
  }
  const [c] = loadFixture<Case[]>("validation_text_cases.json");
  it("stripFences", () => {
    for (const f of c!.fences) {
      expect(stripFences(f.input), JSON.stringify(f.input)).toBe(f.expected_stripped);
    }
  });
  it("sanitizeControlChars", () => {
    for (const f of c!.control_chars) {
      expect(sanitizeControlChars(f.input), JSON.stringify(f.input)).toBe(f.expected);
    }
  });
});

describe("cost estimation parity", () => {
  interface Case {
    name: string;
    config: {
      models: {
        reviewers: { id: string }[];
        synthesizer: { id: string };
        drafter?: { id: string };
      };
      pipeline?: { runs_per_persona?: number };
      personas: string[];
    };
    entries: { name: string; tier: number; send_to: string[] }[];
    documents: Record<string, number>;
    system_prompt_chars: number;
    persona_overlay_chars: Record<string, number>;
    include_drafter: boolean;
    iterations: number;
    expected: {
      model_estimates: {
        model_id: string;
        num_calls: number;
        input_tokens_per_call: number;
        output_tokens_per_call: number;
        input_cost_usd: number;
        output_cost_usd: number;
      }[];
      total_usd: number;
      per_loop_usd: number;
      iterations: number;
    };
  }
  const cases = loadFixture<Case[]>("cost_cases.json");
  it.each(cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    const entries: ManifestEntry[] = c.entries.map((e) => ({
      name: e.name,
      path: `/nonexistent/${e.name}`,
      format: "markdown",
      role: "",
      tier: e.tier as 1 | 2 | 3,
      sendTo: e.send_to,
      critical: false,
      notes: "",
    }));
    const documents: Record<string, DocumentModel> = Object.fromEntries(
      Object.entries(c.documents).map(([name, chars]) => [
        name,
        {
          name,
          role: "r",
          tier: c.entries.find((e) => e.name === name)!.tier,
          content: "",
          pageCount: 1,
          charCount: chars,
          sha256: "0".repeat(64),
          truncated: false,
        },
      ]),
    );
    const estimate = estimatePipelineCost({
      reviewerIds: c.config.models.reviewers.map((r) => r.id),
      synthesizerId: c.config.models.synthesizer.id,
      drafterId: c.config.models.drafter?.id ?? null,
      runsPerPersona: c.config.pipeline?.runs_per_persona ?? 2,
      personas: c.config.personas,
      personaDocChars: (persona) =>
        assembleForPersona(persona, entries, documents).map((d) => d.charCount),
      allDocChars: Object.values(documents).map((d) => d.charCount),
      systemPromptChars: c.system_prompt_chars,
      personaOverlayChars: c.persona_overlay_chars,
      includeDrafter: c.include_drafter,
      iterations: c.iterations,
    });
    expect(estimate.iterations).toBe(c.expected.iterations);
    expect(estimate.modelEstimates.length).toBe(c.expected.model_estimates.length);
    for (let i = 0; i < estimate.modelEstimates.length; i++) {
      const actual = estimate.modelEstimates[i]!;
      const exp = c.expected.model_estimates[i]!;
      expect(actual.modelId).toBe(exp.model_id);
      expect(actual.numCalls).toBe(exp.num_calls);
      expect(actual.inputTokensPerCall).toBe(exp.input_tokens_per_call);
      expect(actual.outputTokensPerCall).toBe(exp.output_tokens_per_call);
      expect(actual.inputCostUsd).toBeCloseTo(exp.input_cost_usd, 6);
      expect(actual.outputCostUsd).toBeCloseTo(exp.output_cost_usd, 6);
    }
    expect(estimateTotalUsd(estimate)).toBeCloseTo(c.expected.total_usd, 6);
    expect(estimatePerLoopUsd(estimate)).toBeCloseTo(c.expected.per_loop_usd, 6);
  });
});
